import type { ExtensionManifest } from "./sdk";

/** Built-in extensions. Their widgets live in src/components/extensions. */
export const EXTENSIONS: ExtensionManifest[] = [
  { id: "solanaos.wallet-tracker", name: "Wallet Tracker", version: "1.0.0", author: "Solana OS", description: "Watch any public wallets and see their latest on-chain activity in your workspace.", category: "Wallets", icon: "Eye", color: "#14f195", permissions: ["wallet:read", "prefs:read", "prefs:write"], widget: { size: "md" }, builtin: true, verified: true },
  { id: "solanaos.whale-alerts", name: "Whale Alerts", version: "1.0.0", author: "Solana OS", description: "Get notified when wallets you follow make large transfers or swaps above your threshold.", category: "Wallets", icon: "Waves", color: "#38bdf8", permissions: ["wallet:read", "notifications", "prefs:read", "prefs:write"], widget: { size: "md" }, builtin: true, verified: true, settings: [{ key: "thresholdUsd", label: "Alert threshold (USD)", type: "number", default: 50000 }] },
  { id: "solanaos.token-scanner", name: "Token Scanner", version: "1.0.0", author: "Solana OS", description: "Paste any mint and get instant risk indicators: authorities, concentration, liquidity and age.", category: "Security", icon: "ScanSearch", color: "#f59e0b", permissions: ["programs:read", "tokens:read"], widget: { size: "md" }, builtin: true, verified: true },
  { id: "solanaos.portfolio-tracker", name: "Portfolio Tracker", version: "1.0.0", author: "Solana OS", description: "Your connected wallet's value, allocation and top holdings at a glance.", category: "Portfolio", icon: "PieChart", color: "#9945ff", permissions: ["portfolio:read", "wallet:read"], widget: { size: "md" }, builtin: true, verified: true },
  { id: "solanaos.pnl-tracker", name: "PnL Tracker", version: "0.9.0", author: "Solana OS", description: "Realized and unrealized profit and loss per token. Requires an indexer provider for cost basis.", category: "Portfolio", icon: "TrendingUp", color: "#22c55e", permissions: ["portfolio:read"], widget: { size: "sm" }, builtin: true, verified: true, requires: "An indexer provider with historical cost basis (e.g. Helius, Birdeye)" },
  { id: "solanaos.prediction-tracker", name: "Prediction Tracker", version: "1.0.0", author: "Solana OS", description: "Follow the prediction markets you care about and see probability changes.", category: "Markets", icon: "Target", color: "#e879f9", permissions: ["markets:read", "prefs:read", "prefs:write"], widget: { size: "md" }, builtin: true, verified: true },
  { id: "solanaos.nft-tracker", name: "NFT Tracker", version: "0.9.0", author: "Solana OS", description: "See the NFTs in your wallet. Rich metadata and floor prices need a DAS-compatible provider.", category: "NFTs", icon: "Images", color: "#fb7185", permissions: ["wallet:read", "portfolio:read"], widget: { size: "sm" }, builtin: true, verified: true },
  { id: "solanaos.defi-dashboard", name: "DeFi Dashboard", version: "1.0.0", author: "Solana OS", description: "Top Solana protocols by TVL and the best-supported yields, updated from DefiLlama.", category: "DeFi", icon: "Landmark", color: "#60a5fa", permissions: ["defi:read"], widget: { size: "lg" }, builtin: true, verified: true },
  { id: "solanaos.network-monitor", name: "Network Monitor", version: "1.0.0", author: "Solana OS", description: "Live slot, throughput and priority fee levels so you know when to transact.", category: "Network", icon: "Activity", color: "#a3e635", permissions: ["network:read"], widget: { size: "sm" }, builtin: true, verified: true },
  { id: "solanaos.security-scanner", name: "Security Scanner", version: "1.0.0", author: "Solana OS", description: "Check a website, wallet or program before you interact with it.", category: "Security", icon: "ShieldCheck", color: "#f97316", permissions: ["programs:read"], widget: { size: "md" }, builtin: true, verified: true },
  { id: "solanaos.price-alerts", name: "Trading Alerts", version: "1.0.0", author: "Solana OS", description: "Set price alerts on any token and get notified when they trigger.", category: "Trading", icon: "BellRing", color: "#facc15", permissions: ["tokens:read", "notifications", "prefs:read", "prefs:write"], widget: { size: "md" }, builtin: true, verified: true },
  { id: "solanaos.social-sentiment", name: "Social Sentiment", version: "0.5.0", author: "Solana OS", description: "Mentions and sentiment for tokens and projects across social platforms.", category: "Trading", icon: "MessagesSquare", color: "#818cf8", permissions: ["tokens:read"], widget: { size: "sm" }, builtin: true, verified: true, requires: "A social data provider (e.g. the X API)" },
  { id: "solanaos.news-monitor", name: "News Monitor", version: "1.0.0", author: "Solana OS", description: "Latest Solana headlines from your chosen sources, filtered by topic.", category: "News", icon: "Newspaper", color: "#94a3b8", permissions: ["news:read", "prefs:read", "prefs:write"], widget: { size: "md" }, builtin: true, verified: true },
  { id: "solanaos.ai-research", name: "AI Research", version: "1.0.0", author: "Solana OS", description: "One-click research briefs on any token or protocol, powered by Solana AI with cited data.", category: "AI", icon: "Sparkles", color: "#c084fc", permissions: ["ai", "tokens:read"], widget: { size: "lg" }, builtin: true, verified: true },
];

export function getExtension(id: string) {
  return EXTENSIONS.find((e) => e.id === id);
}
