import type { AppCategory, AppEntry } from "../types";

/**
 * Curated Solana app registry.
 *
 * This holds *descriptive metadata only* (what an app is, where it lives,
 * who builds it). Usage numbers are never stored here; they come from data
 * providers (DefiLlama etc.) at request time and are labelled with their
 * source. Developers can submit new entries from the Developer Platform.
 */

const a = (e: AppEntry) => e;

export const APPS: AppEntry[] = [
  a({ slug: "jupiter", name: "Jupiter", tagline: "The liquidity aggregator and trading hub of Solana", description: "Jupiter routes swaps across Solana DEXs to find the best price, and offers limit orders, DCA, perpetuals and a launchpad. It is one of the most used applications on Solana.", category: "Trading", subcategories: ["Swapping", "Perpetuals", "Aggregator"], website: "https://jup.ag", appUrl: "https://jup.ag", twitter: "JupiterExchange", discord: "https://discord.gg/jup", github: "https://github.com/jup-ag", docs: "https://dev.jup.ag", launched: 2021, token: { symbol: "JUP", mint: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN" }, programs: [{ id: "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4", name: "Jupiter Aggregator v6" }], developer: "Jupiter", llama: ["jupiter-aggregator", "jupiter-perpetual-exchange", "jupiter"], color: "#19d3a2", featured: true, keywords: ["swap", "dex", "aggregator", "perps", "dca", "limit order"] }),
  a({ slug: "raydium", name: "Raydium", tagline: "AMM and liquidity provider for Solana", description: "Raydium is an automated market maker offering concentrated and standard liquidity pools, token launches and swaps.", category: "DeFi", subcategories: ["Swapping", "Liquidity providing"], website: "https://raydium.io", appUrl: "https://raydium.io/swap", twitter: "RaydiumProtocol", github: "https://github.com/raydium-io", docs: "https://docs.raydium.io", launched: 2021, token: { symbol: "RAY", mint: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R" }, programs: [{ id: "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8", name: "Raydium AMM v4" }, { id: "CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK", name: "Raydium CLMM" }], developer: "Raydium", llama: ["raydium-amm", "raydium"], color: "#6b5cf6", keywords: ["amm", "dex", "liquidity", "launchlab"] }),
  a({ slug: "orca", name: "Orca", tagline: "Concentrated liquidity DEX", description: "Orca is a concentrated-liquidity exchange (Whirlpools) focused on a simple, human-friendly trading experience.", category: "DeFi", subcategories: ["Swapping", "Liquidity providing"], website: "https://www.orca.so", appUrl: "https://www.orca.so", twitter: "orca_so", github: "https://github.com/orca-so", docs: "https://docs.orca.so", launched: 2021, token: { symbol: "ORCA", mint: "orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE" }, programs: [{ id: "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc", name: "Orca Whirlpools" }], developer: "Orca", llama: ["orca-dex", "orca"], color: "#ffd15c", keywords: ["dex", "whirlpools", "clmm"] }),
  a({ slug: "meteora", name: "Meteora", tagline: "Dynamic liquidity for Solana", description: "Meteora provides dynamic liquidity market makers (DLMM), dynamic AMM pools and vaults designed to make liquidity more efficient.", category: "DeFi", subcategories: ["Liquidity providing", "Yield"], website: "https://www.meteora.ag", appUrl: "https://app.meteora.ag", twitter: "MeteoraAG", docs: "https://docs.meteora.ag", launched: 2023, programs: [{ id: "LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo", name: "Meteora DLMM" }], developer: "Meteora", llama: ["meteora-dlmm", "meteora"], color: "#f25c2a", keywords: ["dlmm", "liquidity", "lp"] }),
  a({ slug: "kamino", name: "Kamino", tagline: "Lending, liquidity and leverage", description: "Kamino combines lending and borrowing, automated liquidity vaults and leveraged strategies in one product.", category: "DeFi", subcategories: ["Lending", "Borrowing", "Yield"], website: "https://kamino.finance", appUrl: "https://app.kamino.finance", twitter: "KaminoFinance", docs: "https://docs.kamino.finance", launched: 2022, token: { symbol: "KMNO", mint: "KMNo3nJsBXfcpJTVhZcXLW7RmTwTt4GVFE7suUBo9sS" }, programs: [{ id: "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD", name: "Kamino Lend" }], developer: "Kamino", llama: ["kamino-lend", "kamino-liquidity", "kamino"], color: "#4f7cff", featured: true, keywords: ["lending", "borrow", "vaults", "leverage", "multiply"] }),
  a({ slug: "marginfi", name: "marginfi", tagline: "Decentralized lending", description: "marginfi is a decentralized lending protocol with risk-managed pools for borrowing and lending.", category: "DeFi", subcategories: ["Lending", "Borrowing"], website: "https://www.marginfi.com", appUrl: "https://app.marginfi.com", twitter: "marginfi", docs: "https://docs.marginfi.com", launched: 2022, programs: [{ id: "MFv2hWf31Z9kbCa1snEPYctwafyhdvnV7FZnsebVacA", name: "marginfi v2" }], developer: "mrgn labs", llama: ["marginfi-lending", "marginfi"], color: "#dcdcdc", keywords: ["lending", "borrow"] }),
  a({ slug: "save", name: "Save", tagline: "Lending protocol (formerly Solend)", description: "Save, formerly Solend, is an algorithmic, decentralized lending protocol on Solana.", category: "DeFi", subcategories: ["Lending", "Borrowing"], website: "https://save.finance", twitter: "save_finance", launched: 2021, developer: "Save", llama: ["save", "solend"], color: "#e46f3f", keywords: ["solend", "lending"] }),
  a({ slug: "drift", name: "Drift", tagline: "Perpetuals, spot and borrow/lend", description: "Drift is a decentralized exchange offering perpetual futures, spot trading, borrow/lend and prediction markets (BET).", category: "Trading", subcategories: ["Perpetuals", "Lending", "Prediction"], website: "https://www.drift.trade", appUrl: "https://app.drift.trade", twitter: "DriftProtocol", github: "https://github.com/drift-labs", docs: "https://docs.drift.trade", launched: 2021, token: { symbol: "DRIFT", mint: "DriFtupJYLTosbwoN8koMbEYSx54aFAVLddWsbksjwg7" }, programs: [{ id: "dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH", name: "Drift Protocol v2" }], developer: "Drift Labs", llama: ["drift-trade", "drift"], color: "#9468f7", keywords: ["perps", "futures", "leverage", "bet"] }),
  a({ slug: "phoenix", name: "Phoenix", tagline: "On-chain order book", description: "Phoenix is a fully on-chain central limit order book for spot trading on Solana.", category: "Trading", subcategories: ["Swapping"], website: "https://www.phoenix.trade", twitter: "PhoenixTrade", developer: "Ellipsis Labs", programs: [{ id: "PhoeNiXZ8ByJGLkxNfZRnkUfjvmuYqLR89jjFHGqdXY", name: "Phoenix" }], llama: ["phoenix"], color: "#ff7a45", keywords: ["orderbook", "clob"] }),
  a({ slug: "pump-fun", name: "Pump.fun", tagline: "Token launchpad", description: "Pump.fun lets anyone create and trade new tokens on a bonding curve. Newly launched tokens are highly speculative and frequently lose most of their value.", category: "Trading", subcategories: ["Launchpad"], website: "https://pump.fun", twitter: "pumpdotfun", launched: 2024, programs: [{ id: "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P", name: "Pump.fun" }], developer: "Pump.fun", llama: ["pump.fun", "pumpswap", "pump"], color: "#5fd18b", keywords: ["memecoin", "launchpad", "bonding curve"] }),
  a({ slug: "zeta", name: "Zeta Markets", tagline: "Perpetuals exchange", description: "Zeta offers perpetual futures trading on Solana.", category: "Trading", subcategories: ["Perpetuals"], website: "https://zeta.markets", twitter: "ZetaMarkets", developer: "Zeta", llama: ["zeta-markets", "zeta"], color: "#00d1b2", keywords: ["perps"] }),
  a({ slug: "flash-trade", name: "Flash Trade", tagline: "Pool-to-peer perpetuals", description: "Flash Trade is a perpetuals exchange where traders trade against liquidity pools.", category: "Trading", subcategories: ["Perpetuals"], website: "https://www.flash.trade", twitter: "FlashTrade_", developer: "Flash Trade", llama: ["flash-trade"], color: "#ffcc33", keywords: ["perps", "leverage"] }),
  a({ slug: "marinade", name: "Marinade", tagline: "Liquid and native staking", description: "Marinade lets you stake SOL across a diversified validator set, either natively or through the mSOL liquid staking token.", category: "DeFi", subcategories: ["Staking", "Liquid staking"], website: "https://marinade.finance", appUrl: "https://marinade.finance/app/stake", twitter: "MarinadeFinance", github: "https://github.com/marinade-finance", launched: 2021, programs: [{ id: "MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD", name: "Marinade Finance" }], developer: "Marinade Labs", llama: ["marinade-liquid-staking", "marinade-native", "marinade"], audits: ["Neodyme", "Ackee Blockchain"], color: "#2ec6a4", keywords: ["msol", "stake", "lst"] }),
  a({ slug: "jito", name: "Jito", tagline: "MEV-powered liquid staking", description: "Jito offers JitoSOL, a liquid staking token that includes MEV rewards, and builds validator infrastructure for Solana.", category: "DeFi", subcategories: ["Liquid staking", "Restaking"], website: "https://www.jito.network", appUrl: "https://www.jito.network/staking", twitter: "jito_sol", github: "https://github.com/jito-foundation", launched: 2022, token: { symbol: "JTO", mint: "jtojtomepa8beP8AuQc6eXt5FriJwfFMwQx2v2f9mCL" }, developer: "Jito Labs / Jito Foundation", llama: ["jito-liquid-staking", "jito"], color: "#7ee787", featured: true, keywords: ["jitosol", "mev", "restaking", "stake"] }),
  a({ slug: "sanctum", name: "Sanctum", tagline: "Liquid staking infrastructure", description: "Sanctum unifies liquidity across liquid staking tokens (LSTs) and lets anyone create one.", category: "DeFi", subcategories: ["Liquid staking"], website: "https://sanctum.so", twitter: "sanctumso", developer: "Sanctum", llama: ["sanctum-infinity", "sanctum"], color: "#f7a0d8", keywords: ["lst", "inf", "stake"] }),
  a({ slug: "solayer", name: "Solayer", tagline: "Restaking on Solana", description: "Solayer is a restaking protocol that lets staked SOL secure additional services.", category: "DeFi", subcategories: ["Restaking"], website: "https://solayer.org", twitter: "solayer_labs", developer: "Solayer Labs", llama: ["solayer"], color: "#b5a7ff", keywords: ["restaking", "ssol"] }),
  a({ slug: "perena", name: "Perena", tagline: "Stablecoin infrastructure", description: "Perena builds stablecoin liquidity infrastructure and the USD* yield-bearing stablecoin on Solana.", category: "DeFi", subcategories: ["Stablecoins"], website: "https://perena.org", twitter: "Perena__", developer: "Perena", llama: ["perena"], color: "#68d0ff", keywords: ["stablecoin", "usd*"] }),
  a({ slug: "lulo", name: "Lulo", tagline: "Automated lending yield", description: "Lulo automatically allocates deposits across Solana lending protocols to optimize yield.", category: "DeFi", subcategories: ["Yield", "Lending"], website: "https://lulo.fi", twitter: "uselulo", developer: "Lulo", llama: ["lulo"], color: "#ff8fb1", keywords: ["yield", "savings"] }),
  a({ slug: "streamflow", name: "Streamflow", tagline: "Token vesting and payroll", description: "Streamflow provides token vesting, payment streaming and airdrop distribution tools.", category: "Payments", subcategories: ["Vesting", "Payroll"], website: "https://streamflow.finance", twitter: "streamflow_fi", developer: "Streamflow", llama: ["streamflow"], color: "#1fb8ff", keywords: ["vesting", "streams", "payroll"] }),
  a({ slug: "tensor", name: "Tensor", tagline: "NFT marketplace for traders", description: "Tensor is an NFT marketplace built for active traders with pro-grade tools.", category: "NFTs", website: "https://www.tensor.trade", twitter: "tensor_hq", launched: 2022, developer: "Tensor", color: "#a3e635", keywords: ["nft", "marketplace"] }),
  a({ slug: "magic-eden", name: "Magic Eden", tagline: "Multi-chain NFT marketplace", description: "Magic Eden is an NFT marketplace that started on Solana and now supports several chains.", category: "NFTs", website: "https://magiceden.io", twitter: "MagicEden", launched: 2021, developer: "Magic Eden", color: "#e42575", keywords: ["nft", "marketplace", "ordinals"] }),
  a({ slug: "metaplex", name: "Metaplex", tagline: "The NFT and digital asset standard", description: "Metaplex maintains the token metadata program, Core and Bubblegum (compressed NFTs) standards used by most Solana digital assets.", category: "Developer Tools", subcategories: ["NFTs"], website: "https://www.metaplex.com", twitter: "metaplex", github: "https://github.com/metaplex-foundation", docs: "https://developers.metaplex.com", launched: 2021, programs: [{ id: "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s", name: "Token Metadata" }], developer: "Metaplex Foundation", color: "#ffffff", keywords: ["nft", "standard", "cnft", "core"] }),
  a({ slug: "drip", name: "DRiP", tagline: "Collect free art from creators", description: "DRiP lets creators distribute collectible art and media to fans as compressed NFTs.", category: "NFTs", subcategories: ["Social"], website: "https://drip.haus", twitter: "drip_haus", developer: "DRiP", color: "#ff5f5f", keywords: ["art", "collectibles", "creators"] }),
  a({ slug: "phantom", name: "Phantom", tagline: "Multi-chain crypto wallet", description: "Phantom is a self-custodial wallet for Solana and other chains, available as a browser extension and mobile app.", category: "Wallets", website: "https://phantom.com", twitter: "phantom", launched: 2021, developer: "Phantom Technologies", color: "#ab9ff2", featured: true, keywords: ["wallet", "extension", "mobile"] }),
  a({ slug: "solflare", name: "Solflare", tagline: "Solana-native wallet", description: "Solflare is a self-custodial Solana wallet with staking, swaps and hardware wallet support.", category: "Wallets", website: "https://solflare.com", twitter: "solflare_wallet", developer: "Solflare", color: "#fc7227", keywords: ["wallet", "staking"] }),
  a({ slug: "backpack", name: "Backpack", tagline: "Wallet and exchange", description: "Backpack offers a self-custodial wallet and a regulated exchange.", category: "Wallets", website: "https://backpack.app", twitter: "Backpack", developer: "Backpack", color: "#e33e3f", keywords: ["wallet", "exchange", "xnft"] }),
  a({ slug: "tiplink", name: "TipLink", tagline: "Wallets as links", description: "TipLink lets anyone send crypto through a simple link, with no wallet setup needed for the recipient.", category: "Wallets", subcategories: ["Payments"], website: "https://tiplink.io", twitter: "TipLinkOfficial", developer: "TipLink", color: "#4ba3ff", keywords: ["link", "onboarding", "gift"] }),
  a({ slug: "squads", name: "Squads", tagline: "Multisig and smart accounts", description: "Squads is the multisig standard on Solana, used by teams to secure treasuries and program upgrade authorities.", category: "Security", subcategories: ["Multisig", "DAOs"], website: "https://squads.so", twitter: "SquadsProtocol", github: "https://github.com/Squads-Protocol", launched: 2021, programs: [{ id: "SQDS4ep65T869zMMBKyuUq6aD6EgTu8psMjkvj52pCf", name: "Squads v4" }], developer: "Squads Labs", audits: ["OtterSec", "Neodyme", "Trail of Bits"], color: "#e7e7e7", keywords: ["multisig", "treasury", "smart account"] }),
  a({ slug: "realms", name: "Realms", tagline: "DAO governance", description: "Realms is a DAO dashboard built on the SPL Governance program for proposals, voting and treasury management.", category: "DAOs", website: "https://realms.today", twitter: "Realms_DAOs", developer: "Realms", color: "#b28bff", keywords: ["dao", "governance", "voting"] }),
  a({ slug: "metadao", name: "MetaDAO", tagline: "Futarchy governance and fundraising", description: "MetaDAO uses decision markets (futarchy) to govern organizations and raise capital.", category: "DAOs", subcategories: ["Prediction"], website: "https://metadao.fi", twitter: "MetaDAOProject", developer: "MetaDAO", color: "#f0b429", keywords: ["futarchy", "dao", "markets"] }),
  a({ slug: "helius", name: "Helius", tagline: "RPC, APIs and webhooks", description: "Helius provides RPC nodes, enhanced APIs, webhooks and data streaming for Solana developers.", category: "Infrastructure", subcategories: ["RPC", "Indexing"], website: "https://www.helius.dev", twitter: "heliuslabs", docs: "https://www.helius.dev/docs", developer: "Helius", color: "#ff6b35", keywords: ["rpc", "api", "webhooks", "das", "indexer"] }),
  a({ slug: "triton", name: "Triton One", tagline: "High-performance RPC", description: "Triton One operates RPC infrastructure and open-source data tools such as Yellowstone gRPC.", category: "Infrastructure", subcategories: ["RPC"], website: "https://triton.one", twitter: "triton_one", developer: "Triton One", color: "#2bd9fe", keywords: ["rpc", "grpc", "geyser"] }),
  a({ slug: "pyth", name: "Pyth Network", tagline: "Real-time price oracle", description: "Pyth publishes first-party price data from exchanges and market makers to Solana and other chains.", category: "Infrastructure", subcategories: ["Oracle"], website: "https://www.pyth.network", twitter: "PythNetwork", docs: "https://docs.pyth.network", launched: 2021, token: { symbol: "PYTH", mint: "HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3" }, developer: "Pyth Data Association", color: "#8f6cf6", keywords: ["oracle", "price feed"] }),
  a({ slug: "switchboard", name: "Switchboard", tagline: "Permissionless oracles", description: "Switchboard lets developers build custom data feeds and oracles.", category: "Infrastructure", subcategories: ["Oracle"], website: "https://switchboard.xyz", twitter: "switchboardxyz", developer: "Switchboard", color: "#4f8cff", keywords: ["oracle", "vrf"] }),
  a({ slug: "wormhole", name: "Wormhole", tagline: "Cross-chain messaging", description: "Wormhole is an interoperability protocol connecting Solana to many other blockchains.", category: "Infrastructure", subcategories: ["Bridge"], website: "https://wormhole.com", twitter: "wormhole", launched: 2020, token: { symbol: "W", mint: "85VBFQZC9TZkfaptBWjvUw7YbZjy52A6mjtPGjstQAmQ" }, developer: "Wormhole Foundation", color: "#c8c8ff", keywords: ["bridge", "cross-chain"] }),
  a({ slug: "arcium", name: "Arcium", tagline: "Encrypted computation", description: "Arcium is building a network for encrypted, confidential computation that Solana programs can use.", category: "Infrastructure", subcategories: ["Privacy"], website: "https://www.arcium.com", twitter: "ArciumHQ", developer: "Arcium", color: "#9d7bff", keywords: ["privacy", "mpc", "encryption"] }),
  a({ slug: "solscan", name: "Solscan", tagline: "Block explorer", description: "Solscan is a block explorer for browsing Solana accounts, tokens and transactions.", category: "Developer Tools", subcategories: ["Explorer"], website: "https://solscan.io", twitter: "solscanofficial", developer: "Solscan", color: "#27c6c4", keywords: ["explorer", "transactions"] }),
  a({ slug: "anchor", name: "Anchor", tagline: "Framework for Solana programs", description: "Anchor is the most widely used framework for writing Solana programs in Rust.", category: "Developer Tools", subcategories: ["Framework"], website: "https://www.anchor-lang.com", github: "https://github.com/solana-foundation/anchor", docs: "https://www.anchor-lang.com/docs", developer: "Solana Foundation", color: "#4ab3f4", keywords: ["rust", "framework", "idl"] }),
  a({ slug: "solana-docs", name: "Solana Developer Docs", tagline: "Official developer documentation", description: "Guides, references and cookbooks for building on Solana.", category: "Developer Tools", website: "https://solana.com/docs", docs: "https://solana.com/docs", github: "https://github.com/solana-foundation", developer: "Solana Foundation", color: "#14f195", keywords: ["docs", "tutorial", "learn"] }),
  a({ slug: "crossmint", name: "Crossmint", tagline: "Wallets, payments and minting APIs", description: "Crossmint offers APIs for embedded wallets, stablecoin payments and NFT minting.", category: "Developer Tools", subcategories: ["Payments", "Wallets"], website: "https://www.crossmint.com", twitter: "crossmint", developer: "Crossmint", color: "#22c55e", keywords: ["api", "embedded wallet", "checkout"] }),
  a({ slug: "birdeye", name: "Birdeye", tagline: "Token analytics", description: "Birdeye provides charts, token analytics and data APIs for Solana tokens.", category: "Trading", subcategories: ["Analytics"], website: "https://birdeye.so", twitter: "birdeye_so", developer: "Birdeye", color: "#ff9f1c", keywords: ["charts", "analytics", "api"] }),
  a({ slug: "dexscreener", name: "DEX Screener", tagline: "Real-time DEX charts", description: "DEX Screener tracks trading pairs across DEXs with real-time charts.", category: "Trading", subcategories: ["Analytics"], website: "https://dexscreener.com/solana", twitter: "dexscreener", developer: "DEX Screener", color: "#cfcfcf", keywords: ["charts", "pairs"] }),
  a({ slug: "step-finance", name: "Step Finance", tagline: "Portfolio dashboard", description: "Step Finance aggregates Solana DeFi positions into a single portfolio dashboard.", category: "Other", subcategories: ["Portfolio"], website: "https://www.step.finance", twitter: "StepFinance_", developer: "Step Finance", color: "#6ae67a", keywords: ["portfolio", "dashboard"] }),
  a({ slug: "solana-pay", name: "Solana Pay", tagline: "Open payments standard", description: "Solana Pay is an open standard for payment requests and point-of-sale transactions using stablecoins and SOL.", category: "Payments", subcategories: ["Standard", "Merchants"], website: "https://solanapay.com", docs: "https://docs.solanapay.com", github: "https://github.com/solana-foundation/solana-pay", developer: "Solana Foundation", color: "#14f195", featured: true, keywords: ["qr", "merchant", "checkout", "pos"] }),
  a({ slug: "sphere", name: "Sphere", tagline: "Payments infrastructure", description: "Sphere provides stablecoin payment rails and fiat on/off-ramps for businesses.", category: "Payments", subcategories: ["Infrastructure"], website: "https://spherepay.co", twitter: "sphere_labs", developer: "Sphere Labs", color: "#5b8def", keywords: ["payments", "ramp", "b2b"] }),
  a({ slug: "moonpay-commerce", name: "MoonPay Commerce", tagline: "Crypto checkout (formerly Helio)", description: "MoonPay Commerce (formerly Helio) offers crypto checkout and payment links for merchants, including a Shopify integration.", category: "Payments", subcategories: ["Merchants", "Checkout"], website: "https://www.hel.io", twitter: "hello_helio", developer: "MoonPay", color: "#7c3aed", keywords: ["helio", "checkout", "shopify", "pay links"] }),
  a({ slug: "usdc", name: "USDC", tagline: "Circle's dollar stablecoin", description: "USDC is a fully reserved dollar stablecoin issued by Circle and natively available on Solana.", category: "Payments", subcategories: ["Stablecoins"], website: "https://www.circle.com/usdc", developer: "Circle", token: { symbol: "USDC", mint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v" }, color: "#2775ca", keywords: ["stablecoin", "dollar"] }),
  a({ slug: "pyusd", name: "PayPal USD", tagline: "PayPal's stablecoin", description: "PYUSD is a dollar stablecoin issued by Paxos for PayPal, available on Solana as a Token-2022 asset.", category: "Payments", subcategories: ["Stablecoins"], website: "https://www.paypal.com/pyusd", developer: "Paxos / PayPal", token: { symbol: "PYUSD", mint: "2b1kV6DkPAnxd5ixfnxCpjxmKwqjjaYmCZfHsFu24GXo" }, color: "#0070e0", keywords: ["stablecoin", "paypal"] }),
  a({ slug: "helium", name: "Helium", tagline: "Decentralized wireless network", description: "Helium runs community-powered IoT and mobile networks, coordinated on Solana since 2023.", category: "DePIN", website: "https://www.helium.com", twitter: "helium", token: { symbol: "HNT", mint: "hntyVP6YFm1Hg25TN9WGLqM12b8TQmcknKrdu1oxWux" }, developer: "Helium Foundation / Nova Labs", color: "#474dff", featured: true, keywords: ["wireless", "5g", "iot", "hotspot"] }),
  a({ slug: "hivemapper", name: "Hivemapper", tagline: "Decentralized mapping", description: "Hivemapper builds a global map from dashcam imagery contributed by drivers who earn HONEY.", category: "DePIN", website: "https://hivemapper.com", twitter: "Hivemapper", developer: "Hivemapper", color: "#f5c400", keywords: ["maps", "dashcam", "honey"] }),
  a({ slug: "render", name: "Render Network", tagline: "Decentralized GPU rendering", description: "Render Network connects creators who need GPU compute with node operators who provide it.", category: "DePIN", subcategories: ["AI"], website: "https://rendernetwork.com", twitter: "rendernetwork", token: { symbol: "RENDER", mint: "rndrizKT3MK1iimdxRdWabcF7Zg7AR5T4nud4EkHBof" }, developer: "Render Network Foundation", color: "#ff3b3b", keywords: ["gpu", "rendering", "compute"] }),
  a({ slug: "io-net", name: "io.net", tagline: "Decentralized GPU cloud", description: "io.net aggregates GPUs into a decentralized cloud for AI and ML workloads.", category: "AI", subcategories: ["DePIN"], website: "https://io.net", twitter: "ionet", developer: "io.net", color: "#e2e2e2", keywords: ["gpu", "ai", "compute"] }),
  a({ slug: "nosana", name: "Nosana", tagline: "GPU marketplace for AI inference", description: "Nosana is a marketplace for GPU compute focused on AI inference workloads.", category: "AI", subcategories: ["DePIN"], website: "https://nosana.com", twitter: "nosana_ai", developer: "Nosana", color: "#10e80c", keywords: ["gpu", "inference"] }),
  a({ slug: "grass", name: "Grass", tagline: "Bandwidth-sharing network", description: "Grass lets users share unused internet bandwidth to power public web data collection for AI.", category: "DePIN", subcategories: ["AI"], website: "https://www.getgrass.io", twitter: "getgrass_io", developer: "Wynd Labs", color: "#bfff00", keywords: ["bandwidth", "data", "ai"] }),
  a({ slug: "solana-agent-kit", name: "Solana Agent Kit", tagline: "Toolkit for AI agents on Solana", description: "An open-source toolkit by SendAI for connecting AI agents to Solana protocols.", category: "AI", subcategories: ["Developer Tools"], website: "https://www.sendai.fun", github: "https://github.com/sendaifun/solana-agent-kit", twitter: "sendaifun", developer: "SendAI", color: "#ff4d6d", keywords: ["agents", "ai", "sdk"] }),
  a({ slug: "elizaos", name: "ElizaOS", tagline: "Open-source agent framework", description: "ElizaOS is an open-source framework for building autonomous AI agents, widely used in the Solana ecosystem.", category: "AI", website: "https://elizaos.ai", github: "https://github.com/elizaOS/eliza", twitter: "elizaOS", developer: "Eliza Labs", color: "#ff7a00", keywords: ["agents", "framework"] }),
  a({ slug: "star-atlas", name: "Star Atlas", tagline: "Space strategy game", description: "Star Atlas is a space exploration and strategy game with an on-chain economy.", category: "Gaming", website: "https://staratlas.com", twitter: "staratlas", developer: "ATMTA", color: "#e0b050", keywords: ["game", "metaverse"] }),
  a({ slug: "aurory", name: "Aurory", tagline: "Tactical RPG", description: "Aurory is a tactical role-playing game with on-chain collectibles.", category: "Gaming", website: "https://aurory.io", twitter: "AuroryProject", developer: "Aurory", color: "#48c9ff", keywords: ["game", "rpg"] }),
  a({ slug: "dialect", name: "Dialect", tagline: "Blinks and notifications", description: "Dialect builds Blinks (shareable blockchain links) and messaging/notification infrastructure.", category: "Social", subcategories: ["Developer Tools"], website: "https://www.dialect.to", twitter: "saydialect", developer: "Dialect Labs", color: "#ffffff", keywords: ["blinks", "actions", "notifications"] }),
  a({ slug: "tapestry", name: "Tapestry", tagline: "Social graph protocol", description: "Tapestry provides a social graph and profiles that Solana apps can share.", category: "Social", website: "https://www.usetapestry.dev", developer: "Tapestry", color: "#8b5cf6", keywords: ["social graph", "profiles"] }),
  a({ slug: "audius", name: "Audius", tagline: "Decentralized music streaming", description: "Audius is a music streaming platform owned by artists and fans.", category: "Social", website: "https://audius.co", twitter: "audius", developer: "Audius", color: "#cc0fe0", keywords: ["music", "streaming"] }),
  a({ slug: "ondo", name: "Ondo Finance", tagline: "Tokenized treasuries and stocks", description: "Ondo issues tokenized real-world assets such as USDY (backed by US Treasuries) and tokenized equities.", category: "RWA", subcategories: ["Treasury products", "Tokenized stocks"], website: "https://ondo.finance", twitter: "OndoFinance", developer: "Ondo Finance", llama: ["ondo-yield-assets", "ondo-finance", "ondo"], color: "#1a4dff", keywords: ["usdy", "treasuries", "rwa", "stocks"] }),
  a({ slug: "xstocks", name: "xStocks", tagline: "Tokenized equities", description: "xStocks by Backed offers tokenized stocks and ETFs as SPL tokens, tradable on Solana DEXs.", category: "RWA", subcategories: ["Tokenized stocks"], website: "https://xstocks.com", developer: "Backed Finance", llama: ["xstocks", "backed"], color: "#e5e5e5", keywords: ["stocks", "equities", "etf"] }),
  a({ slug: "maple", name: "Maple", tagline: "On-chain credit", description: "Maple is an institutional lending platform; syrupUSDC brings its yield to Solana.", category: "RWA", subcategories: ["Credit"], website: "https://maple.finance", twitter: "maplefinance", developer: "Maple Labs", llama: ["maple", "syrup"], color: "#ff6b00", keywords: ["credit", "lending", "syrup"] }),
  a({ slug: "parcl", name: "Parcl", tagline: "Real estate price exposure", description: "Parcl lets users trade exposure to real estate price indices of cities.", category: "RWA", subcategories: ["Real-world assets"], website: "https://www.parcl.co", twitter: "Parcl", developer: "Parcl", llama: ["parcl"], color: "#5b7cfa", keywords: ["real estate", "index"] }),
  a({ slug: "hedgehog", name: "Hedgehog Markets", tagline: "Prediction markets", description: "Hedgehog offers prediction markets on crypto, sports and culture.", category: "Prediction", website: "https://hedgehog.markets", twitter: "HedgehogMarket", developer: "Hedgehog", color: "#f6a609", keywords: ["prediction", "betting", "markets"] }),
  a({ slug: "drift-bet", name: "Drift BET", tagline: "Prediction markets on Drift", description: "BET is Drift's prediction market product where outcomes trade as on-chain markets.", category: "Prediction", website: "https://www.drift.trade", appUrl: "https://app.drift.trade/bet", twitter: "DriftProtocol", developer: "Drift Labs", color: "#9468f7", keywords: ["prediction", "bet", "election"] }),
  a({ slug: "sec3", name: "Sec3", tagline: "Security audits and tooling", description: "Sec3 audits Solana programs and builds automated security scanners.", category: "Security", subcategories: ["Audits"], website: "https://www.sec3.dev", developer: "Sec3", color: "#00c2ff", keywords: ["audit", "security"] }),
  a({ slug: "ottersec", name: "OtterSec", tagline: "Security audits", description: "OtterSec audits smart contracts and protocols across the Solana ecosystem.", category: "Security", subcategories: ["Audits"], website: "https://osec.io", developer: "OtterSec", color: "#7f8cff", keywords: ["audit", "security"] }),
  a({ slug: "rugcheck", name: "RugCheck", tagline: "Token risk reports", description: "RugCheck generates automated risk reports for Solana tokens.", category: "Security", website: "https://rugcheck.xyz", developer: "RugCheck", color: "#27ae60", keywords: ["token scanner", "rug"] }),
  a({ slug: "solana-mobile", name: "Solana Mobile", tagline: "Crypto-native phones", description: "Solana Mobile makes the Saga and Seeker phones with a built-in Seed Vault and dApp Store.", category: "Other", subcategories: ["Hardware"], website: "https://solanamobile.com", twitter: "solanamobile", developer: "Solana Mobile", color: "#14f195", keywords: ["phone", "seeker", "saga", "dapp store"] }),
  a({ slug: "bonk", name: "Bonk", tagline: "Community dog coin", description: "BONK is a community memecoin that became one of the most widely held tokens on Solana. Memecoins are highly volatile.", category: "Other", subcategories: ["Community"], website: "https://bonkcoin.com", twitter: "bonk_inu", token: { symbol: "BONK", mint: "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263" }, developer: "BONK community", color: "#f7a41d", keywords: ["memecoin", "community"] }),
];

export function getApp(slug: string): AppEntry | undefined {
  return APPS.find((x) => x.slug === slug);
}

export function appsByCategory(cat: AppCategory): AppEntry[] {
  return APPS.filter((x) => x.category === cat || x.subcategories?.includes(cat));
}

export function appForProgram(programId: string): AppEntry | undefined {
  return APPS.find((x) => x.programs?.some((p) => p.id === programId));
}

export function appForToken(mint: string): AppEntry | undefined {
  return APPS.find((x) => x.token?.mint === mint);
}

export function domainOf(url: string): string {
  try {
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    return url;
  }
}

export const KNOWN_DOMAINS = [...new Set(APPS.flatMap((x) => [x.website, x.appUrl].filter(Boolean).map((u) => domainOf(u!))))];
